import Head from 'next/head'
import { Button, Card, Divider, Input } from 'antd'
import MainLayout from '../../../components/layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>DiffusionPro</title>
        <meta name="description" content="Generated by DiffusionPro" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <div>
          <Card
            title="Home"
            bordered={false}
            style={{ height: 500 }}
          >
            <p className='mb-4'>Search Image</p>
            <Input placeholder="Search" style={{ width: 300 }} />
            <Button type="primary" style={{ marginLeft: 10 }}>
              Search
            </Button>

            <Divider />
          </Card>
        </div>
      </MainLayout>
    </>
  )
}
