import { useEffect, useState } from "react";
import Head from "next/head";
import { Card, Row, Col, Divider } from "antd";
import { Autoplay, Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import Link from "next/link";

import Footer from "../../components/footer";


export default function Home() {
  
  const [isLogin, setIsLogin] = useState(false);

  useEffect(() => { checking(); });

  const checking = () => {
    let user = localStorage.getItem("test");
    if (user === "test") {
      setIsLogin(true);
    } else {
      window.location.href = "/login";
    }
  };

  return (
    <>
      <Head>
        <title>DiffusionPro</title>
        <meta name="description" content="Generated by DiffusionPro" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <>
        <div style={{ display: isLogin ? "block" : "none" }} className="backbg">
          <div className="backbg-color">
            <>
              <header>
                <div className="header-sv1">
                  <div>
                  </div>
                  <div className="header-sv1-right">
                    <div className="navigation">
                      <Link className="button" href="/login">
                        <img className="img-person" src="/assets/person.png" />
                        <div className="logout">LOGOUT</div>
                      </Link>
                    </div>
                  </div>
                </div>
              </header>

              <div>
                <div className="header-div">
                  <Row>
                    <Col xs={24} sm={24} md={24} lg={24} xl={24}>
                      <div
                        style={{
                          padding: 24,
                          paddingLeft: "10%",
                          marginTop: 65,
                          marginRight: 10,
                        }}
                      >
                        <div>
                          <h2 style={{ color: "white", fontSize: 50 }}>
                            GENERATE <br />
                            CHANGE
                            <br />
                            MANIPULATE
                            <br />
                          </h2>
                        </div>

                        <div
                          style={{
                            marginTop: 20,
                            width: 760,
                            borderTop: "2px solid #bbb",
                          }}
                        />

                        <div style={{ marginTop: 20 }}>
                          <span style={{ color: "white", fontSize: 26 }}>
                            Exploring the Potential of Stable Diffusion and
                            Control Net Models <br />
                            for Image Manipulation and Beyond: Techniques and
                            Applications
                          </span>
                        </div>

                        <div style={{ marginTop: 30 }} onClick={() => { window.location.href = "/base-models/text-to-image" }}>
                          <button className="glowing-btn">
                            <span className="glowing-txt">
                              G<span className="faulty-letter">E</span>T STARTED
                            </span>
                          </button>
                        </div>
                      </div>
                    </Col>
                  </Row>
                </div>

                <div style={{ padding: 24, marginTop: 50 }}>
                
                  {/* Swiper Components */}
                  <section>
                    <div
                      style={{
                        margin: 10,
                      }}
                    >
                      <Swiper
                        slidesPerView={2}
                        autoplay={{
                          delay: 2500,
                          disableOnInteraction: false,
                        }}
                        breakpoints={{
                          320: {
                            slidesPerView: 1,
                          },
                          375: {
                            slidesPerView: 1,
                          },
                          425: {
                            slidesPerView: 1,
                          },
                          640: {
                            slidesPerView: 2,
                          },
                          1024: {
                            slidesPerView: 6,
                          },
                        }}
                        spaceBetween={30}
                        pagination={false}
                        modules={[Pagination, Autoplay]}
                        style={{
                          height: 300,
                        }}
                      >
                        <SwiperSlide
                          style={{
                            cursor: "pointer",
                            height: 250,
                            padding: 0,
                          }}
                          onClick={() =>
                            (window.location.href = "/base-models/text-to-image")
                          }
                        >
                          <Card
                            className="cardClass1"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Text to Image</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() =>
                            (window.location.href = "/base-models/text-to-image-anime")
                          }
                        >
                          <Card
                            className="cardClass2"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Anything V3: Anime</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/base-models/image-to-image")}
                        >
                          <Card
                            className="cardClass3"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Image to Image</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/canny-image")}
                        >
                          <Card
                            className="cardClass4"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet Canny</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/mlsd")}
                        >
                          <Card
                            className="cardClass10"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet MLSD</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/hed")}
                        >
                          <Card
                            className="cardClass5"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet HED</p>
                        </SwiperSlide>

                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/lineart")}
                        >
                          <Card
                            className="cardClass6"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet LineArt</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/normal-bae")}
                        >
                          <Card
                            className="cardClass7"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet NormalMap</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/post-to-image")}
                        >
                          <Card
                            className="cardClass8"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet OpenPose</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/scribble")}
                        >
                          <Card
                            className="cardClass9"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet Scribble</p>
                        </SwiperSlide>

                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/shuffle")}
                        >
                          <Card
                            className="cardClass11"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet Shuffle</p>
                        </SwiperSlide>
                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/control-nets/softedge")}
                        >
                          <Card
                            className="cardClass12"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Controlnet SoftEdge</p>
                        </SwiperSlide>

                        <SwiperSlide
                          style={{ cursor: "pointer", height: 250 }}
                          onClick={() => (window.location.href = "/base-models/text-to-image")}
                        >
                          <Card
                            className="cardClass14"
                            style={{ height: 250 }}
                          ></Card>
                          <p>Waifu Diffusion: Anime</p>
                        </SwiperSlide>
                      </Swiper>
                    </div>
                  </section>

                  <Divider />

                </div>

                {/* Footer */}
                <Footer />

              </div>
            </>
          </div>
        </div>
      </>
    </>
  );
}
